### ISSUE TITLE
Standard page type is broken

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#35]
For some reason I don't understand, `<% if $ElementalArea %>` craps itself when there's no method with this name. That's in `theme/starter/Layout/Page.ss`. We've applied `ElementalPageExtension` on`BlocksPage`, not on `Page`. So this breaks standard page type rendering.

Option A: Move `Layout/Page.ss` into `app/templates`, remove section about ElementalArea
Option B: Move `ElementalPageExtension` to `Page`, make a `PageWithoutBlocks` type as a subclass (instead of having a `BlocksPage`)
Option C: Do some smart overloading of this method in Page.php

**Comment by sminnee** [comment]
Advise against Option B because, as I understand it, the main use-case of PageWithotBlocks is modules that subclass Page.

Option C might be as simple as 
```
class Page {
  function ElementalArea() { return null; }
}

class BlocksPage extends Page {
  /** Restore the behaviour of the magic method broken by Page::ElementalArea() */
  function ElementalArea() { return $this->getComponents('ElementalArea'); }
}
```

**Comment by maxime-rainville** [comment]
How about Option D: Figure out why `<% if $ElementalArea %>` craps itself and fix it.

**Comment by chillu** [comment]
Please raise a core bug if it's not fixable in core in <1h.

**Comment by unclecheese** [comment]
Fixed on UAT: http://bambusad-uat.sites.silverstripe.com/about/just-a-page

Issue: `BlocksPage` has no `BlocksPageController`.

* When the request is handled, it first processes `/about/`, which is a `BlocksPage`.
* `ModelAsController::controller_for($blocksPage)` gets back a `PageController`
* `PageController::create($blocksPage)` results in the `failover` for the controller being `BlocksPage`
* `hasMethod('SomeMethodAppliedToOnlyBlockPage')` returns `true` because the failover has it.
* `$pageController->handleRequest('not-a-blockpage')` now thinks it has a method it doesn't.

Ticket forthcoming.

**Comment by unclecheese** [comment]
Issue posted here: https://github.com/silverstripe/silverstripe-framework/issues/9140
