### ISSUE TITLE
Icon block to feature illustrated content in a small space

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#36]
## Overview

As a demo content writer, I want to make the content interesting to the reader in order to create a better understanding of the feature set that we're presenting

## Acceptance Criteria

 * I can add up to four items in a block
 * Each item can contain an image, a title and content
 * Images are resized automatically
 * Items are displayed in columns on desktop, and work well in mobile views

## Notes

 * We've got this block on silverstripe.com already: https://www.silverstripe.com/platform/expert-support/
 * Look in the community for existing blocks

## PRs
 - [x] https://github.com/silverstripe/bambusa-theme/pull/25
 - [x] https://github.com/silverstripe/bambusa-installer/pull/47
 - [x] https://github.com/silverstripe/bambusa-installer/pull/58
- [x] https://github.com/silverstripe/bambusa-theme/pull/36
- [x] https://github.com/silverstripe/bambusa-installer/pull/60

**Comment by chillu** [comment]
https://github.com/scott1702/silverstripe-handyblocks/tree/master/src/Blocks

**Comment by dnsl48** [comment]
I have moved over the one we're using on silverstripe.com, which is https://github.com/silverstripeltd/ss-shared/blob/develop/src/Blocks/MultiColumnBlock.php

**Comment by dnsl48** [comment]
Google search didn't give me anything suitable "as is" among the community driven modules and the 2 pointer card didn't give me feeling like I could "play" with different ones and try to "fit" some of those for our purpose.

**Comment by chillu** [comment]
I would've preferred the image to be a separate upload field, so authors don't need to worry about exact sizing between multiple items. It would've also enabled us to resize images smaller for responsive/mobile views. Which was implied in the AC of "Images are resized automatically", and discussed in backlog planning. But in the spirit of getting this project done, I'll accept it as-is.

**Comment by dnsl48** [comment]
> and discussed in backlog planning

Sorry, I wasn't in that backlog planning, missed all the details :)

**Comment by chillu** [comment]
Worked through the current limitations with Karl, and he's OK with them. Since we don't need content to write about this as a feature (rather we use the feature to jazz up existing content), there's no further work on this. 

@clarkepaul @newleeland Can one of you check with Karl on design?

**Comment by clarkepaul** [comment]
This block meets the acceptance but I wouldn't have chosen it as it can only handle up to 5 items in a row before it breaks into a list (we want to hold 12 so not so bad looking—3 sets of 4 items). The layout gets weird with three items at a medium screen size where you get two items above a single item (looks slightly weirder when content is left-aligned). Because the items in each row are fixed to the row they won't flow on to the next row if there is no room meaning it isn't very responsive. If a user wants to rearrange or move items to another row it's a lot of work for the author.

Ideally, we would have a block which can take as many items as is required by the content author and not let the layout dictate the content so much. As this is a demo we need to expect people to add and remove content/columns from the block.

The other column block on https://www.silverstripe.com/silverstripe-cms/features-and-benefits/ permitted as many items as you needed and defaulted to a 3 column layout—not as rigid.

We'll have a play and see if we can use it in a good way, its a bit late for any changes now I guess.

**Comment by chillu** [comment]
LGTM. Serge worked with Karl and Olivia when doing those revisions. There's no written record here on what was actually required (revised ACs), so it's a bit hard for me to accept this as working as intended. But I can't fault anything in the current implementation either :)
