### ISSUE TITLE
Raygun: no configuration found

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#71]
This demo didn't get Raygun error monitoring, which is really bad since we won't find out if anything goes wrong there: https://ragingstags-sscom.demo.silverstripe.cc/.

**Comment by dnsl48** [comment]
I have checked that `ssdemo/snapshots` snapshot `21718` has `SS_RAYGUN_APP_KEY` defined. Though, dev/build on my demo doesn't seem to be having it in the list of env vars registered by EnvVarSnapshot. Need to check what snapshot ID is getting used for demos.

**Comment by dnsl48** [comment]
Ok, I think I have guessed what the problem is.
The [custom HTTPApplication middleware](https://github.com/silverstripe/bambusa-installer/blob/master/public/index.php#L25) we use to restore env vars [isn't being registered in CLI mode](https://github.com/silverstripe/silverstripe-framework/blob/4/cli-script.php#L22). So, CLI based dev/build removes the raygun app key.

**Comment by dnsl48** [comment]
> Ok, I think I have guessed what the problem is.
The custom HTTPApplication middleware we use to restore env vars isn't being registered in CLI mode. So, CLI based dev/build removes the raygun app key.

I've checked it locally and it's not correct. I'm going to look further.

**Comment by dnsl48** [comment]
fixed (for new demos)

**Comment by chillu** [comment]
Closing, but strongly relying on peer review here. As Max said in the PR, it's hard to test this. I'm monitoring the error stream for absence of this error heh.

**Comment by dnsl48** [comment]
Yes, that's why I've created a new demo and checked it works fine after it's been merged :)
