### ISSUE TITLE
PHP memory limit too low, breaks on image upload

### ISSUE THREAD

**Issue by chillu** [silverstripe/bambusa-installer#85]
https://app.raygun.com/crashreporting/1po60pm/errors/3886025152?dateFrom=2019-09-25T02%3A12%3A00.000Z&dateTo=2019-10-02T01%3A12%3A44.000Z

Looks like there's only 128MB of `memory_limit`, which seems to crash on larger image resizes. We try to predict when GD would run out of memory in core, but the logic seems to fail here. Of course, we shouldn't resize images in process on the web worker, but that's a different story.

**Comment by dnsl48** [comment]
[I've increased the memory limit up to 256M](https://github.com/silverstripe/bambusa-installer/commit/cd531b5bfc4df0dbc9321f75ba562e644455e4a0) (for the following demos).
I think that's reasonable enough.
Otherwise, I guess we should come up with an external queue based resizing that could be done outside of the application server (lambdas or 3rd party services).
I don't see any other sensible options how we could deal with that issue at this point.

**Comment by chillu** [comment]
Awesome, thanks!
